# Generated by Django 3.2.6 on 2021-08-13 22:37

from django.db import migrations, models
import menu.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[menu.validators.validate_price])),
                ('quantity', models.IntegerField(default=0, validators=[menu.validators.validate_quantity])),
                ('modifiers', models.JSONField(blank=True, default=dict, validators=[menu.validators.validate_modifiers])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.JSONField(blank=True, default=list, validators=[menu.validators.validate_order_items])),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6, validators=[menu.validators.validate_price])),
                ('note', models.TextField(default='')),
            ],
        ),
    ]
